[Eth]
NetworkId = 90000
SyncMode = "full"
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
TxLookupLimit = 2350000
TransactionHistory = 2350000
StateHistory = 90000
LightPeers = 100
DatabaseCache = 488
DatabaseFreezer = ""
TrieCleanCache = 146
TrieDirtyCache = 244
TrieTimeout = 3600000000000
SnapshotCache = 97
Preimages = false
FilterLogCacheSize = 32
EnablePreimageRecording = false
RPCGasCap = 50000000
RPCEVMTimeout = 5000000000
RPCTxFeeCap = 1e+00

[Eth.Miner]
Etherbase = "0x2d862b18bc5816b438c49931f8264926c2144190"
GasFloor = 0
GasCeil = 30000000
GasPrice = 1000000000
Recommit = 2000000000
NewPayloadTimeout = 2000000000

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 5120
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.BlobPool]
Datadir = "blobpool"
Datacap = 10737418240
PriceBump = 100

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
MaxPrice = 500000000000
IgnorePrice = 2

[Node]
DataDir = "node03"
IPCPath = "geth.ipc"
HTTPPort = 8549
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["admin","eth","miner","net","web3","clique","txpool","personal"]
AuthAddr = "localhost"
AuthPort = 8553
AuthVirtualHosts = ["localhost"]
WSPort = 8550
WSModules = ["admin","eth","miner","net","web3","clique","txpool","personal"]
GraphQLVirtualHosts = ["localhost"]
BatchRequestLimit = 1000
BatchResponseMaxSize = 25000000

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
DiscoveryV4 = true
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = ["enode://01b73aae7eac71a7795b2cf115de9ce0d3358f1906d4eb0551929a233749f4283dfe73e6a1db5c95980c3e78f2e98d7ca32d3262a991d4c8078ec2a174ffd02a@127.0.0.1:30303",
"enode://dcd5f127c4a5cefba205d7b380dc7dc6b6026e614909787daf38f6de94ee2ba768140dd2f8a39bc9354da46ab3cda9328db11debaa9961139962531a8845e3f5@127.0.0.1:30304",
"enode://7583eba74fe3080075214e652c0ddb1c498faa63362a583244c16073c58b9b7e9b9679db5f6e48c9a9771ef4716be10bc8b581a90ce67a05772df60445e7e18a@127.0.0.1:30305"]
TrustedNodes = []
ListenAddr = ":30305"
DiscAddr = ""
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Metrics]
HTTP = "127.0.0.1"
Port = 6062
InfluxDBEndpoint = "http://localhost:8088"
InfluxDBDatabase = "geth"
InfluxDBUsername = "test"
InfluxDBPassword = "test"
InfluxDBTags = "host=localhost"
InfluxDBToken = "test"
InfluxDBBucket = "geth"
InfluxDBOrganization = "geth"
