version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ether
      POSTGRES_PASSWORD: softclaw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
